In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
data_file ='makeSenseOfCensus.csv'

In [4]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [5]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [7]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]

np.concatenate((data,new_record), axis=0)

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [14]:
age = data[:,0]

In [15]:
age

array([39., 50., 38., 53., 28., 37., 49., 52., 31., 42., 37., 30., 23.,
       32., 40., 34., 25., 32., 38., 43., 40., 54., 35., 43., 59., 56.,
       19., 54., 39., 49., 23., 20., 45., 30., 22., 48., 21., 19., 31.,
       48., 31., 53., 24., 49., 25., 57., 53., 44., 41., 29., 25., 18.,
       47., 50., 47., 43., 46., 35., 41., 30., 30., 32., 48., 42., 29.,
       36., 28., 53., 49., 25., 19., 31., 29., 23., 79., 27., 40., 67.,
       18., 31., 18., 52., 46., 59., 44., 53., 49., 33., 30., 43., 57.,
       37., 28., 30., 34., 29., 48., 37., 48., 32., 76., 44., 47., 20.,
       29., 32., 17., 30., 31., 42., 24., 38., 56., 28., 36., 53., 56.,
       49., 55., 22., 21., 40., 30., 29., 19., 47., 20., 31., 35., 39.,
       28., 24., 38., 37., 46., 38., 43., 27., 20., 49., 61., 27., 19.,
       45., 70., 31., 22., 36., 64., 43., 47., 34., 33., 21., 52., 48.,
       23., 71., 29., 42., 68., 25., 44., 28., 45., 36., 39., 46., 18.,
       66., 27., 28., 51., 27., 28., 27., 21., 34., 18., 33., 44

In [16]:
min_age = np.min(age)
min_age

17.0

In [17]:
max_age = np.max(age)
max_age

90.0

In [18]:
mean_age = np.mean(age)

In [19]:
mean_age

38.051

In [20]:
std_dev = np.std(age)

In [21]:
std_dev

13.342803266180612

In [25]:
race_0 = data[data[:,2]==0, :]
race_1 = data[data[:,2]==1, :]
race_2 = data[data[:,2]==2, :]
race_3 = data[data[:,2]==3, :]
race_4 = data[data[:,2]==4, :]

In [26]:
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

In [28]:
print(len_0)
print(len_1)
print(len_2)
print(len_3)
print(len_4)

10
27
110
6
847


In [29]:
race_coll = np.array([len_0, len_1, len_2, len_3, len_4])

In [30]:
smallest_pop = np.min(race_coll)

In [34]:
minority_race= list(race_coll).index(smallest_pop)

In [35]:
minority_race

3

In [40]:
senior_citizens = data[data[:,0]>60,:]
senior_citizens

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

In [41]:
working_hours_sum = np.sum(senior_citizens[:,7])
working_hours_sum

13.0

In [42]:
senior_citizens_len = len(senior_citizens)
senior_citizens_len

61

In [44]:
avg_working_hours = working_hours_sum/senior_citizens_len
print(avg_working_hours*100)

21.311475409836063


In [45]:
high = data[data[:,1]>10,:]

In [46]:
high

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [28., 13.,  2., ...,  0., 40.,  0.],
       ...,
       [45., 14.,  4., ...,  0., 45.,  0.],
       [48., 13.,  4., ...,  0., 58.,  1.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [47]:
low = data[data[:,1]<10,:]

In [48]:
low

array([[38.,  9.,  4., ...,  0., 40.,  0.],
       [53.,  7.,  2., ...,  0., 40.,  0.],
       [49.,  5.,  2., ...,  0., 16.,  0.],
       ...,
       [47.,  9.,  4., ...,  0., 50.,  1.],
       [35.,  9.,  4., ...,  0., 45.,  0.],
       [56.,  9.,  4., ...,  0., 55.,  1.]])

In [52]:
avg_pay_high = np.mean(high[:,7])
avg_pay_high

0.42813455657492355

In [56]:
avg_pay_low = np.mean(np.mean(low[:,7]))
avg_pay_low

0.12723214285714285